### ISSUE TITLE
Call os.rename directly instead of through shutil.move

### ISSUE THREAD

**Issue by pavlix** [brainsik/json-store#4]
The `shutil.move` function exists specifically to support non-atomic move across filesystems. Atomic move is done using `os.rename` that refuses to move across filesystems. On the other hand you would then need to ensure your temporary file is created on the same filesystem.

**Comment by amotl** [comment]
Dear Pavel,

with your suggestion, you are referring to a potential race condition in the `sync` method, specifically when using `json-store` in a concurrent environment?

With kind regards,
Andreas.

**Comment by brainsik** [comment]
I believe this is more about code correctness than an actual issue. `shutil.move()` uses `os.rename()` when the source and destination are on the same filesystem and we have that since the tempfile is created in the same directory as the existing store:

```python
        dirname = os.path.dirname(self.path)
        return NamedTemporaryFile(mode="w", prefix=prefix, dir=dirname, delete=False)
```

I think the argument is that since we only want to use `os.rename`, we should just call it directly. That's arguably more correct, but there's no actual atomicity issue here.

It's a good suggestion. I'll temper the title a bit.
